- planning/communication-plan.md
> Minju communication Plan

- planning/communication-plan.md
> Updated Haneefa availabilty

- planning/communication-plan.md
> added dnyanu's communication plan

- .cspell.json
- planning/communication-plan.md
> Elias; Communication plan

- planning/communication-plan.md
>  i added my avaialble time on this week

- planning/user-personas.md
>  I finished the student user persona

- planning/backlog.md
>  i added the could have part of the backlog

- README.md
- planning/backlog.md
#Backlog should have
- OUR IMPACT
- OUR CORE VALUES
- OUR SUCCESS STORIES
> Adding ShouldHaves in the backlog file

- planning/backlog.md
>  I changed the format to match the should have

- .cspell.json
- planning/backlog.md
> PR_Musthave

- planning/design.md
> added website design

- planning/backlog.md
> Backlogmusthave

- planning/backlog.md
- planning/development-strategy.md
> Development strategy 

- .vscode/settings.json
- index.html
- package-lock.json
- package.json
- styles/style.css
> Adding Contact form and the google map

- index.html
> fixed the errors

- index.html
- styles/style.css
>  made colors similar to dnyando section

- index.html
> removed reapet code

- index.html
- styles/style.css
> update all home page with responsive

- index.html
- styles/style.css
> Adding the new contact form and map using css

- index.html
- styles/style.css
> responsive header update

- index.html
- styles/fontello.css
- styles/style.css
> PR_Our core values css

- index.html
- styles/style.css
> three d home page with responsive

- index.html
- styles/style.css
> Success stories of HYF Students

- index.html
- styles/style.css
> update info and media query

- planning/design.md
> Create Volunteer subpage design

- index.html
- styles/style.css
> Added slide show animation to stories

- pages/about.html
- pages/supportus.html
- planning/retrospective.md
> Adding Retrospective file

- pages/about.html
- styles/style.css
> adjusting the scrolling by using overflow property

- styles/style.css
>  Making about page responsive

- index.html
- styles/style.css
> fixed navbar error

- .cspell.json
- planning/design.md
> Digitalents-design

- pages/digitalents.html
- pages/program.html
- pages/supportus.html
- pages/volunteer.html
> link all pages to each other

- pages/team.html
- styles/style.css
> update project team page

- pages/about.html
- styles/style.css
> Fixing the overflow to the about page

- pages/volunteer.html
- styles/style.css
> fixed volunteer page error
